// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Projekt_sbd.Data;

#nullable disable

namespace Projekt_sbd.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt_sbd.Models.Grade", b =>
                {
                    b.Property<int>("IdOcena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOcena"));

                    b.Property<DateTime>("DataOceny")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdPrzedmiot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdStudent")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Komentarz")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Wartosc")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdOcena");

                    b.HasIndex("IdPrzedmiot");

                    b.HasIndex("IdStudent");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("Projekt_sbd.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<DateTime?>("DataUrodz")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NrIndeksu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdStudent");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Projekt_sbd.Models.Subject", b =>
                {
                    b.Property<int>("IdPrzedmiot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrzedmiot"));

                    b.Property<int>("IdNauczyciel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Semestr")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPrzedmiot");

                    b.HasIndex("IdNauczyciel");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("Projekt_sbd.Models.Teacher", b =>
                {
                    b.Property<int>("IdNauczyciel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNauczyciel"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdNauczyciel");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("Projekt_sbd.Models.Grade", b =>
                {
                    b.HasOne("Projekt_sbd.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("IdPrzedmiot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_sbd.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Projekt_sbd.Models.Subject", b =>
                {
                    b.HasOne("Projekt_sbd.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("IdNauczyciel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Projekt_sbd.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Projekt_sbd.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Projekt_sbd.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
